export const SUBJECTS = [
    "Quran",
    "Islamic Studies",
    "Arabic",
    "English",
    "Mathematics",
    "Science",
    "Social Studies",
    "Computer Science",
    "Art",
    "PE",
];

export const GRADES = [
    "Grade 1",
    "Grade 2",
    "Grade 3",
    "Grade 4",
    "Grade 5",
    "Grade 6",
    "Grade 7",
    "Grade 8",
    "Grade 9",
    "Grade 10",
    "Grade 11",
    "Grade 12"
];

export const WEEKS = [
    "Week 1",
    "Week 2",
    "Week 3",
    "Week 4",
    "Week 5",
    "Week 6",
    "Week 7",
    "Week 8",
    "Week 9",
    "Week 10",
    "Week 11",
    "Week 12",
    "Week 13",
    "Week 14",
    "Week 15",
    "Week 16",
    "Week 17",
    "Week 18",
    "Week 19",
    "Week 20",
]